### ISSUE TITLE
What is the preferred was to pass assets around?

### ISSUE THREAD

**Issue by Timtam** [a1phyr/assets_manager#13]
Please excuse my lack of knowledge, i'm just starting out with Rust and am still struggling with some things concept-wise, so feel free to refer me to whichever source might be helpful here.
I'm starting development on a game where I've got a workspace with different crates, one doing the ui work and another implementing the game logic. The UI should be able to receive an asset, preferably a sound asset, and play that whenever a button gets selected or clicked. The game crate should then initialize a menu and hand over the asset. But what would be the actual asset type I should pass along? The AssetGuard, the asset itself (e.g. a Vorbis type)?
Could you give me an example of a method which accepts and uses a sound asset parameter, or even better, a struct which stores a value of that type to be used later?
Thank you!

**Comment by a1phyr** [comment]
Hello !
Sorry for this late answer.

First, it depends on whether you want hot-reloading or not. If not, you can pass the sound around directly, possibly by cloning it if necessary. If you use `assets_manager` sound types like [`asset::Vorbis`](https://docs.rs/assets_manager/latest/assets_manager/asset/struct.Vorbis.html), they are made so they are cheap to clone.

If you want hot-reloading, you can use `AssetHandle` and `.read()` it when you need to use the inner value. It may be difficult due to its lifetime, though. In this case, you can pass the asset id (as a `String` or a cheap to clone [`SharedString`](https://docs.rs/assets_manager/latest/assets_manager/struct.SharedString.html)) and use it to load the sound from the cache whenever you need it.

However, you should generally avoid passing an `AssetGuard` around, as it locks the asset and prevents reloading it.

**Comment by a1phyr** [comment]
Does it answer your question ? If not, feel free to re-open this issue.
