### ISSUE TITLE
Loading from Zipped asset

### ISSUE THREAD

**Issue by savire** [a1phyr/assets_manager#20]
Hi mate, on your description its said that it could read assets from zipped format.
Is there any example to do that?
Also can we just simply load asset into a binary string like u8 so that it can be passed around easily to other libs?
Cheers.

**Comment by a1phyr** [comment]
Hi !

Loading files from a zip archive is simple, just use [`assets_manager::source::Zip`](https://docs.rs/assets_manager/latest/assets_manager/source/struct.Zip.html) as the `Source` of your AssetCache:

```rust
// Open the zip file
let zip = assets_manager::source::Zip::open("assets.zip")?;

// Create the cache that loads from the zip
let cache = assets_manager::AssetCache::with_source(zip);

// Load assets
let asset = cache.load::<String>("example.hello")?;
```

For your second question, you can make a wrapper around `Vec<u8>` and implement `Asset` for it:

```rust
// Define a newtype
struct Bytes(Vec<u8>);

impl From<Vec<u8>> for Bytes {
    fn from(bytes: Vec<u8>) -> Self {
        Self(bytes)
    }
}

// Implement `Asset` for it
impl assets_manager::Asset for Bytes {
    type Loader = assets_manager::loader::LoadFrom<Vec<u8>, assets_manager::loader::BytesLoader>;
    const EXTENSION: &'static str = "bin";
}

// Then load your asset
let handle = cache.load::<Bytes>("example.data")?;
```

**Comment by savire** [comment]
Wow, thank you so much for the examples mate. Really appreciates it.
One last question. From the documentation link you gave above it says: "Warning: This will clone the reader each time it is read, so you should ensure that is cheap to clone (eg not Vec<u8>)."
Does that mean that it won't cached the last file being read and will read the zip file again whenever its being requested?
Should I be worried even if I'm serving it locally?
Once again thank you verymuch for the reply.

**Comment by a1phyr** [comment]
> Does that mean that it won't cached the last file being read and will read the zip file again whenever its being requested?

`Zip` (nor any `Source`) does not do any caching when reading files, caching is the role of an `AssetCache` (or its thread-local variant).
The warning means that the reader (of type `R`) that `Zip<R>` uses is cloned (with `Clone` trait) each time a file is read. If `R` is `io::Cursor<Vec<u8>>`, the cost will be pretty high, which is why you should use something like `assets_manager::SharedBytes` which is made for this purpose.

>  Should I be worried even if I'm serving it locally?

I am unsure that I correctly understand your question. 
If you talk about serving your zip file from a server, then the best thing to do is probably put it all in a `SharedBytes`, then create a `Zip` from it.

**Comment by savire** [comment]
Thank you so much mate. I think I understand now. I'll be very careful later when implementing it for my project needs. Cheers.
