### ISSUE TITLE
[question] Asset: Send + Sync

### ISSUE THREAD

**Issue by pum-purum-pum-pum** [a1phyr/assets_manager#8]
`Asset` trait requires type to implement Send + Sync, but Is there a way to use it with types that don't implement Sync + Send without Arc Mutex?

**Comment by a1phyr** [comment]
Unfortunately this is not possible, because in this case `AssetCache` could not be `Send + Sync`.

As you said, if your type is only `Send`, you can wrap it in a `Mutex` to make it `Sync` too (`Arc` has nothing to do with making values `Send`/`Sync`). However, if it is neither `Send` nor `Sync` (such as `Rc`), you cannot use it with `assets_manager` at the moment.

However, it is interesting idea to move the `Send + Sync` bound to the methods of `AssetCache`, and create `LocalCache`, an equivalent of `AssetCache` that accept all `Asset` types but is `!Send + !Sync`.

**Comment by a1phyr** [comment]
I tried to move the `Send + Sync` bound from `Asset` to `AssetCache` methods to ease eventual future additions such as `LocalCache`, but it would require too much work and interface redesign.

I am still open to do something like this in the future, but I close this at the moment.
